#!/bin/bash
#SBATCH --job-name=phase_shifts
#SBATCH --output=/fred/oz002/vdimarco/jumps/jumps_or_no_jumps/jobs
#SBATCH --ntasks=1
#SBATCH --time=00:45:00
#SBATCH --tmp=4g
#SBATCH --mem-per-cpu=8g
#SBATCH --array=1-10

ml conda
conda activate ent15y
module load tempo2/0759584

python /fred/oz002/vdimarco/jumps/jumps_or_no_jumps/sims/final_norn/output/real_$SLURM_ARRAY_TASK_ID/phase_shifts_parallel_all_small.py
