#!/bin/bash
#SBATCH --job-name=OS_same
#SBATCH --ntasks=1
#SBATCH --time=00:05:00
#SBATCH --tmp=4g
#SBATCH --mem-per-cpu=8g
#SBATCH --array=0-99

ml conda
conda activate ent15y 

cd /fred/oz002/vdimarco/jumps/jumps_or_no_jumps/sims/final_small_jumps_norednoise/output/real_$SLURM_ARRAY_TASK_ID
 
python calculate_OS_parallel_all_small.py
