#!/bin/bash
#SBATCH --job-name=scriptmaster_big
#SBATCH --ntasks=1
#SBATCH --time=00:10:00
#SBATCH --tmp=4g
#SBATCH --mem-per-cpu=8g
#SBATCH --array=0-99

source ~/.setup_ptasim

cd /fred/oz002/vdimarco/jumps/jumps_or_no_jumps/sims/final_no_jumps_norednoise_emptyjson/scripts

chmod +x process_real_$SLURM_ARRAY_TASK_ID

csh /fred/oz002/vdimarco/jumps/jumps_or_no_jumps/sims/final_no_jumps_norednoise_emptyjson/scripts/process_real_$SLURM_ARRAY_TASK_ID
